# frozen_string_literal: true

source "https://rubygems.org"

gem "awesome_print", "~> 1.9.2"
gem "pry", "~> 0.14.1"

gem "rspec", "~> 3.10.0", require: false
gem "rubocop", "~> 1.23.0", require: false
gem "rubocop-performance", "~> 1.12.0", require: false
gem "rubocop-rspec", "~> 2.6.0", require: false
