# frozen_string_literal: true

source "https://rubygems.org"

gem "awesome_print", "~> 1.8.0"
gem "pry", "~> 0.13.1"

gem "rspec", "~> 3.10.0", require: false
gem "rubocop", "~> 1.5.1", require: false
gem "rubocop-performance", "~> 1.9.1", require: false
gem "rubocop-rspec", "~> 2.0.1", require: false
