# frozen_string_literal: true

source "https://rubygems.org"

gem "awesome_print", "~> 1.9.2"
gem "pry", "~> 0.14.1"

gem "rspec", "~> 3.12.0", require: false
gem "rubocop", "~> 1.39.0", require: false
gem "rubocop-performance", "~> 1.15.0", require: false
gem "rubocop-rspec", "~> 2.15.0", require: false
gem "rubocop-sorbet", "~> 0.6.11", require: false

gem "sorbet", group: :development
gem "sorbet-runtime"
gem "tapioca", require: false, group: :development

gem "matrix", "~> 0.4.2"
