# frozen_string_literal: true

source "https://rubygems.org"

gem "pry", "~> 0.12.2"

gem "rubocop", "~> 0.77.0", require: false
gem "rubocop-performance", "~> 1.5.1", require: false
gem "rubocop-rspec", "~> 1.37.0", require: false
gem "rspec", "~> 3.9.0", require: false
